services:
  polyedge:
    build: .
    restart: unless-stopped
    environment:
      - PORT=8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.polyedge.rule=Host(`api.nshrt.com`)
      - traefik.http.routers.polyedge.entrypoints=web,websecure
      - traefik.http.routers.polyedge.tls=true
      - traefik.http.routers.polyedge.tls.certresolver=mytlschallenge
      - traefik.http.services.polyedge.loadbalancer.server.port=8080
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
    name: n8n_default
